services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_HOST=0.0.0.0
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "3001:3000"
    volumes:
      - ./server:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/mydatabase

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432" 