services:
  client:
    build:
      context: ./client
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${ENV}
      - VITE_HOST=${CLIENT_HOST}
      - BASE_API_URL=${CLIENT_BASE_API_URL}
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - RAILS_ENV=${ENV}
      - DATABASE_URL=${SERVER_DATABASE_URL}
      - JWT_SECRET_KEY=${SERVER_JWT_SECRET_KEY}
      - OPENAI_API_KEY=${SERVER_OPENAI_API_KEY}
      - PORT=${SERVER_PORT}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    ports:
      - "${DB_PORT}:5432"