services:
  client:
    build:
      context: ./client
      dockerfile: ./Dockerfile
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${ENV}
      - VITE_HOST=${CLIENT_HOST}
      - BASE_API_URL=${CLIENT_BASE_API_URL}
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    volumes:
      - ./server:/app
    working_dir: /app
    depends_on:
      - db
    environment:
      - RAILS_ENV=${ENV}
      - DATABASE_URL=${SERVER_DATABASE_URL}
      - JWT_SECRET_KEY=${SERVER_JWT_SECRET_KEY}
      - OPENAI_API_KEY=${SERVER_OPENAI_API_KEY}
      - PORT=${SERVER_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "${DATABASE_PORT}:5432"