services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - "${CLIENT_PORT}:80"
    environment:
      - NODE_ENV=production
      - VITE_HOST=${CLIENT_HOST}
      - BASE_API_URL=${CLIENT_BASE_API_URL}
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
      args:
        - RAILS_ENV=production
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - RAILS_ENV=production
      - DATABASE_URL=${SERVER_DATABASE_URL}
      - JWT_SECRET_KEY=${SERVER_JWT_SECRET_KEY}
      - OPENAI_API_KEY=${SERVER_OPENAI_API_KEY}
      - PORT=${SERVER_PORT}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DB_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DB_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 