name: monthly-budget-dev
region: nyc
alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
databases:
- engine: PG
  name: db-monthly-budget-dev
features:
- buildpack-stack=ubuntu-22
ingress:
  rules:
  - component:
      name: monthly-budget-server
    match:
      path:
        prefix: /
services:
- dockerfile_path: server/Dockerfile
  envs:
  - key: SERVER_PORT
    scope: RUN_AND_BUILD_TIME
    value: "80"
  - key: JWT_SECRET_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:Ha4Txn8ebOr2BntAqTn9sY94o9GdCRcW:qZGWc3UQ7mdylNx2FBbTM/v3g9m4uwsRiBw2Al94TrOqKb9zcJ5Nfsp91d4uYf8hkjDEDpWFAkwgXJCNeSdrnQcz0x/7yFRfhOc7NbXRRK6JVc/QUk+8++dzn3kh08sOGdxwX6wWHSCRuRa0up3wEHWr0tNHtY9Tr0tBY9Ir4IxA/U0mbwNViVFM+wrkPSTi]
  - key: OPENAI_API_KEY
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:wWPCl0ZnPNHUBZhQYg1rutLwWDAi9/dl:thCX93F3Gx/UhPVu8FYi6Egwty5eDEWT3ReozbZmNGAaklbYreeuILQmYt6JG/srbpofd72x0AgUCcY6hRf4EuhwEi5rvlKacyo/C5kiUMPs/ttwZxXQjFSaxXOoW1idD1z1zDcBS2ukfqt22W6zUcOpYT84aXI6Eo+Z8Fk4r8DCMYam3PxpO8szraftX9B9LY0BclvPW28JheETXK4JbKhZSxcRpgoOSCkF4HLNUj4sv5JH]
  - key: DATABASE_URL
    scope: RUN_TIME
    value: ${db-monthly-budget-dev.DATABASE_URL}
  - key: RAILS_ENV
    scope: RUN_AND_BUILD_TIME
    value: development
  - key: CLIENT_BASE_URL
    scope: RUN_AND_BUILD_TIME
    value: https://monthly-budget-dev-wri3l.ondigitalocean.app/api/v1
  github:
    branch: develop
    deploy_on_push: true
    repo: gaboluque/monthly_budget
  http_port: 80
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-1gb
  name: monthly-budget-server
  source_dir: server
