json.id budget_item.id
json.name budget_item.name
json.amount budget_item.amount
json.category budget_item.category
json.last_paid_at budget_item.last_paid_at
json.is_paid budget_item.paid_this_month?
json.is_pending budget_item.pending?
json.created_at budget_item.created_at
json.updated_at budget_item.updated_at
